name: Build Underthesea Linux ARM64 Wheels

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      version:
        description: 'Version of Underthesea to build (e.g., 6.8.4)'
        required: true
        default: '6.8.4' # Default to misaki dep

# Add permissions needed to create releases
permissions:
  contents: write

jobs:
  build_linux_arm64:
    name: Build Underthesea Linux ARM64 Wheels
    runs-on: ubuntu-24.04-arm # Target Linux ARM64

    strategy:
      fail-fast: false
      matrix:
        # Build for relevant Python versions (underthesea-core supports 3.8-3.11)
        python-version: ["3.9", "3.10", "3.11"] 

    steps:
      - name: Checkout repository (Optional but good practice)
        uses: actions/checkout@v4 

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable # Use maintained action
        with:
          toolchain: stable
          # profile: minimal # dtolnay action doesn't use profile, defaults are usually fine
          # override: true # dtolnay action handles overrides automatically

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential # Common build tools
          pip install maturin # Install maturin here

      - name: Build wheel
        run: |
          mkdir -p wheelhouse
          # Use --no-build-isolation since we've installed maturin and Rust already
          pip wheel --no-build-isolation --wheel-dir wheelhouse underthesea==${{ github.event.inputs.version }}

      - name: Upload Linux Wheels Artifact
        uses: actions/upload-artifact@v4
        with:
          name: underthesea-linux-wheels-${{ matrix.python-version }}
          path: wheelhouse/*.whl

  release:
    name: Create GitHub Release for Linux ARM64
    needs: [build_linux_arm64] # Run after the build job completes
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts # Download all artifacts into the 'artifacts' directory

      - name: List downloaded files # Optional: for debugging
        run: ls -R artifacts

      - name: Create Release and Upload Wheels
        uses: softprops/action-gh-release@v2
        with:
          tag_name: underthesea-v${{ github.event.inputs.version }}-linux-arm64 # Specific tag
          name: Underthesea v${{ github.event.inputs.version }} Linux ARM64 Wheels # Specific name
          files: artifacts/*/*.whl # Upload all .whl files from all subdirectories in artifacts
          make_latest: true # Mark as latest if desired, or false if these are supplementary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
