name: Build SudachiPy Wheels

on:
  push:
    tags:
      - "sudachipy-v*" # Trigger on tags like sudachipy-v0.6.10
  workflow_dispatch: # Allow manual triggering
    inputs:
      version:
        description: 'Version of SudachiPy to build (e.g., 0.6.10)'
        required: true
        default: '0.6.10'

jobs:
  build:
    name: Build SudachiPy Wheels
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest] # Re-added linux/arm64
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.23.2

      - name: Build wheels
        run: |
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT: "PIP_NO_CACHE_DIR=off"
          CIBW_BEFORE_BUILD: "pip install setuptools-rust"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
          CIBW_SKIP: "pp*"  # Skip unsupported platforms like PyPy

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}