name: Build All Misaki Dependencies

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      version:
        description: 'Version of Misaki to build'
        required: true
        default: '0.9.4'

jobs:
  build_amd64_deps:
    name: Build AMD64 Dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]  # Only build for Python 3.10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl git gnupg lsb-release wget cmake
          cmake --version
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          python -m pip install --upgrade pip setuptools wheel pip-tools maturin

      - name: Build all wheels and dependencies
        env:
          CMAKE_POLICY_VERSION_MINIMUM: 3.5
        run: |
          mkdir -p wheelhouse
          # Build pyopenjtalk first to handle CMake policy issue
          pip wheel --wheel-dir wheelhouse pyopenjtalk==0.4.0 || echo "Pyopenjtalk wheel build failed, will try with full misaki install"
          # Build underthesea-core with maturin explicitly
          pip wheel --wheel-dir wheelhouse underthesea-core==1.0.4 || echo "underthesea-core wheel build failed, will try with full misaki install"
          # Build mojimoji separately to ensure it's included
          pip wheel --wheel-dir wheelhouse mojimoji
          # Download and build misaki with all its dependencies
          pip wheel --wheel-dir wheelhouse "misaki[en,ja,ko,zh,vi]==${{ github.event.inputs.version }}"
          # List all wheels for debugging
          find wheelhouse -name "*.whl" | sort > wheelhouse/wheel_list.txt
          echo "All wheels built:"
          cat wheelhouse/wheel_list.txt
          echo "Total wheel count: $(cat wheelhouse/wheel_list.txt | wc -l)"

      - name: Upload AMD64 Dependencies
        uses: actions/upload-artifact@v4
        with:
          name: misaki-all-deps-amd64-py${{ matrix.python-version }}
          path: wheelhouse/*.whl

  build_arm64_deps:
    name: Build ARM64 Dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]  # Only build for Python 3.10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARM64 dependencies image
        id: build_image # Add an ID to reference the image tag later if needed
        run: |
          docker buildx build --platform linux/arm64 \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            --build-arg PACKAGE_VERSION=${{ github.event.inputs.version }} \
            -f .github/workflows/misaki-deps.Dockerfile \
            --load \
            -t misaki-deps-builder:${{ matrix.python-version }} .

      - name: Extract ARM64 wheels from image
        run: |
          mkdir -p wheelhouse
          # Create a temporary container from the built image
          CONTAINER_ID=$(docker create misaki-deps-builder:${{ matrix.python-version }})
          # Copy the wheels from the container's /wheelhouse to the host's wheelhouse
          # The '/.' after /wheelhouse ensures the *contents* are copied
          docker cp ${CONTAINER_ID}:/wheelhouse/. wheelhouse/
          # Remove the temporary container
          docker rm ${CONTAINER_ID}
          echo "--- Contents of wheelhouse after copy (ARM64) ---"
          ls -la wheelhouse
          echo "Total wheel count: $(find wheelhouse -type f -name "*.whl" | wc -l)"
          echo "-------------------------------------------------"

      - name: Upload ARM64 Dependencies
        uses: actions/upload-artifact@v4
        with:
          name: misaki-all-deps-arm64-py${{ matrix.python-version }}
          path: wheelhouse/*.whl

  create_deps_release:
    name: Create Dependencies Release
    needs: [build_amd64_deps, build_arm64_deps]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For release creation
    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files
        run: |
          find artifacts -type f -name "*.whl" | sort
          echo "Total wheel count: $(find artifacts -type f -name "*.whl" | wc -l)"

      - name: Prepare release assets
        run: |
          mkdir -p release_assets
          cp -f artifacts/misaki-all-deps-*/*.whl release_assets/ || true
          echo "--- Contents of release_assets ---"
          ls -la release_assets
          echo "Total wheel count: $(find release_assets -type f -name "*.whl" | wc -l)"
          echo "----------------------------------"

      - name: Create Release and Upload All Dependencies
        uses: softprops/action-gh-release@v2
        with:
          tag_name: misaki-deps-v${{ github.event.inputs.version }}
          name: Misaki v${{ github.event.inputs.version }} All Dependencies
          files: release_assets/*.whl
          body: |
            # Misaki Dependencies

            This release contains all dependencies required by Misaki v${{ github.event.inputs.version }} for both ARM64 and AMD64 architectures.
            
            These pre-built wheels make it easy to install Misaki and all its dependencies in environments where compilation might be difficult or time-consuming.

            ## Usage in Dockerfile
            ```dockerfile
            # Download and install all pre-built wheels
            COPY --from=ghcr.io/your-org/misaki-deps:${{ github.event.inputs.version }} /wheelhouse /wheelhouse
            RUN pip install --no-index --find-links=/wheelhouse misaki[en,ja,ko,zh,vi]==${{ github.event.inputs.version }}
            ```
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_push_container:
    name: Push Dependencies Container
    needs: [build_amd64_deps, build_arm64_deps]
    runs-on: ubuntu-latest
    permissions:
      packages: write  # For pushing to GHCR
    strategy:
      matrix:
        python-version: ["3.10"]  # Only build for Python 3.10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare AMD64 wheels directory
        id: amd64-wheels
        run: |
          mkdir -p wheelhouse-amd64-py${{ matrix.python-version }}
          cp -f artifacts/misaki-all-deps-amd64-py${{ matrix.python-version }}/*.whl wheelhouse-amd64-py${{ matrix.python-version }}/ || true
          AMD64_COUNT=$(find wheelhouse-amd64-py${{ matrix.python-version }} -type f -name "*.whl" | wc -l)
          echo "count=${AMD64_COUNT}" >> $GITHUB_OUTPUT
          echo "::notice title=AMD64 Wheels::Found ${AMD64_COUNT} wheels for Python ${{ matrix.python-version }}"
          
      - name: Prepare ARM64 wheels directory
        id: arm64-wheels
        run: |
          mkdir -p wheelhouse-arm64-py${{ matrix.python-version }}
          cp -f artifacts/misaki-all-deps-arm64-py${{ matrix.python-version }}/*.whl wheelhouse-arm64-py${{ matrix.python-version }}/ || true
          ARM64_COUNT=$(find wheelhouse-arm64-py${{ matrix.python-version }} -type f -name "*.whl" | wc -l)
          echo "count=${ARM64_COUNT}" >> $GITHUB_OUTPUT
          if [ "${ARM64_COUNT}" -gt 0 ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "::notice title=ARM64 Wheels::Found ${ARM64_COUNT} wheels for Python ${{ matrix.python-version }}"
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "::warning title=ARM64 Wheels::No wheels found for Python ${{ matrix.python-version }}"
          fi

      - name: Set up QEMU # Add QEMU setup
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx # Add Buildx setup
        uses: docker/setup-buildx-action@v3
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_PACKAGES }}  # Use PAT instead of GITHUB_TOKEN

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/misaki-deps-multiarch.Dockerfile # Use the new Dockerfile
          platforms: linux/amd64,linux/arm64 # Build both platforms
          push: true
          tags: ghcr.io/remsky/prebuilt_tts_wheels/misaki-deps:${{ github.event.inputs.version }}-py${{ matrix.python-version }} # Push the final tag
          build-args: | # Pass Python version to Dockerfile
            PYTHON_VERSION=${{ matrix.python-version }}
          cache-from: type=gha # Enable GHA cache read
          cache-to: type=gha,mode=max # Enable GHA cache write
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Pre-built wheels for Misaki TTS
            org.opencontainers.image.licenses=MIT
