name: Build SudachiPy ARM64 Linux Wheels

on:
  workflow_dispatch: # Allow manual triggering
    inputs:
      version:
        description: 'Version of SudachiPy to build (e.g., 0.6.10)'
        required: true
        default: '0.6.10'

jobs:
  build:
    name: Build SudachiPy ARM64 Linux Wheels
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Create wheel directory
        run: mkdir -p wheelhouse

      - name: Build ARM64 wheels with Docker
        run: |
          for PY_VERSION in 3.10 3.11 3.12 3.13; do
            docker run --platform linux/arm64 --rm -v $(pwd)/wheelhouse:/wheels -e PYTHON_VERSION=$PY_VERSION arm64v8/python:${PY_VERSION}-slim bash -c '
              apt-get update && apt-get install -y --no-install-recommends \
                curl \
                build-essential \
              && apt-get clean \
              && rm -rf /var/lib/apt/lists/* \
              && curl --proto '\'='=https'\'' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y \
              && export PATH=$HOME/.cargo/bin:$PATH \
              && pip install --upgrade pip setuptools wheel \
              && pip wheel --wheel-dir /wheels sudachipy==${{ github.event.inputs.version }}
            '
          done

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: sudachipy-v${{ github.event.inputs.version }}-arm64
          name: SudachiPy v${{ github.event.inputs.version }} ARM64 Linux Wheels
          files: wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}